# Assignment: Classify the badges dataset with decision tree classifier
In this assignment, Use the badges dataset from the UCI repository and pick a vectorizer of their choice to structure the data. Next they have to apply decision tree classifier by trying different maximum depths for the tree and evaluating last 10 instances to verify results.

In [141]:
corpus = open('D:\\badges.data').read() #Reading the dataset

In [142]:
docs = corpus.split('\n') #Spliting in new line

In [143]:
X, y = [], []
for doc in docs:
    l = doc[:1]
    i = doc[2:]
    X.append(i)
    y.append(l)

In [144]:
from sklearn.feature_extraction.text import TfidfVectorizer #Using TFIDF text representation technique

In [145]:
vec = TfidfVectorizer()

In [146]:
matrix_X = vec.fit_transform(X) #Convert input file into matrix form

In [147]:
matrix_X

<294x523 sparse matrix of type '<class 'numpy.float64'>'
	with 607 stored elements in Compressed Sparse Row format>

In [148]:
from sklearn.tree import DecisionTreeClassifier #Decision Tree Classifier

In [165]:
dt = DecisionTreeClassifier(max_depth = 2) # max_depth is used to define level of branching on features

In [166]:
dt.fit(matrix_X[:285], y[:285]) #Taining model with some part of dataset from 0 to 284

DecisionTreeClassifier(max_depth=2)

In [167]:
dt.predict(matrix_X[285:]) #Testing model using last 10 remaining dataset 285 to 294

array(['+', '+', '+', '+', '+', '+', '-', '+', '+'], dtype='<U1')

In [168]:
dt.predict_proba(matrix_X[285:]) #Probability of Decision Tree classifier

array([[0.72924188, 0.27075812],
       [0.72924188, 0.27075812],
       [0.72924188, 0.27075812],
       [0.72924188, 0.27075812],
       [0.72924188, 0.27075812],
       [0.72924188, 0.27075812],
       [0.        , 1.        ],
       [0.72924188, 0.27075812],
       [0.72924188, 0.27075812]])

In [169]:
dt = DecisionTreeClassifier(max_depth = 3) # max_depth is used to define level of branching on features

In [170]:
dt.fit(matrix_X[:285], y[:285]) #Taining model with some part of dataset from 0 to 284

DecisionTreeClassifier(max_depth=3)

In [171]:
dt.predict(matrix_X[285:]) #Testing model using last 10 remaining dataset 285 to 294

array(['+', '+', '+', '+', '+', '+', '-', '+', '+'], dtype='<U1')

In [172]:
dt.predict_proba(matrix_X[285:]) #Probability of Decision Tree classifier

array([[0.73722628, 0.26277372],
       [0.73722628, 0.26277372],
       [0.73722628, 0.26277372],
       [0.73722628, 0.26277372],
       [0.73722628, 0.26277372],
       [0.73722628, 0.26277372],
       [0.        , 1.        ],
       [0.73722628, 0.26277372],
       [0.73722628, 0.26277372]])

In [173]:
dt = DecisionTreeClassifier(max_depth = 4) # max_depth is used to define level of branching on features

In [174]:
dt.fit(matrix_X[:285], y[:285]) #Taining model with some part of dataset from 0 to 284

DecisionTreeClassifier(max_depth=4)

In [175]:
dt.predict(matrix_X[285:]) #Testing model using last 10 remaining dataset 285 to 294

array(['+', '+', '+', '+', '+', '+', '-', '+', '+'], dtype='<U1')

In [176]:
dt.predict_proba(matrix_X[285:]) #Probability of Decision Tree classifier

array([[0.74264706, 0.25735294],
       [0.74264706, 0.25735294],
       [0.74264706, 0.25735294],
       [0.74264706, 0.25735294],
       [0.74264706, 0.25735294],
       [0.74264706, 0.25735294],
       [0.        , 1.        ],
       [0.74264706, 0.25735294],
       [0.74264706, 0.25735294]])